name: Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Azure using workload identity federation
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      # Deploy the Bicep template
      - name: Deploy Bicep code
        run: |
          az deployment sub create \
            --location switzerlandnorth \
            --template-file bicep-code/main.bicep \
            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
